/* Generated from EscapeArc_Final_Master_Itineraries.xlsx */
const tours = [
  {
    "id": "kashmir-calm-flow",
    "name": "Kashmir Calm Flow",
    "type": "national",
    "duration": "3N/4D",
    "price": 8599,
    "priceLabel": "₹8,599–₹35,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Srinagar → Gulmarg → Pahalgam",
    "category": "Leisure",
    "region": "Kashmir",
    "travelType": "Leisure",
    "audience": "Couples, first-timers, short scenic trips",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / houseboat",
    "itinerarySummary": "D1 Arrival / start at Srinagar | D2 Move to Gulmarg / sightseeing | D3 Local excursion / leisure | D4 Departure / return",
    "originalItinerary": "Beautiful Kashmir 3N/4D",
    "pageTitle": "Kashmir Calm Flow | EscapeArc Kashmir Tour",
    "metaDescription": "Kashmir Calm Flow: 3N/4D EscapeArc kashmir experience covering Srinagar → Gulmarg → Pahalgam. Built for couples, first-timers, short scenic trips.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "kashmir-lake-+-valley-loop",
    "name": "Kashmir Lake & Valley Loop",
    "type": "national",
    "duration": "4N/5D",
    "price": 8599,
    "priceLabel": "₹8,599–₹35,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Srinagar → Gulmarg → Pahalgam → Sonmarg",
    "category": "Leisure",
    "region": "Kashmir",
    "travelType": "Leisure",
    "audience": "Families, photography, fuller valley circuit",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / houseboat",
    "itinerarySummary": "D1 Arrival / start at Srinagar | D2 Proceed to Gulmarg | D3 Proceed to Pahalgam | D4 Local sightseeing / leisure | D5 Departure / return",
    "originalItinerary": "Beautiful Kashmir 4N/5D",
    "pageTitle": "Kashmir Lake & Valley Loop | EscapeArc Kashmir Tour",
    "metaDescription": "Kashmir Lake & Valley Loop: 4N/5D EscapeArc kashmir experience covering Srinagar → Gulmarg → Pahalgam → Sonmarg. Built for families, photography, fuller valley circuit.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "kashmir-slow-escape",
    "name": "Kashmir Slow Escape",
    "type": "national",
    "duration": "5N/6D",
    "price": 8599,
    "priceLabel": "₹8,599–₹35,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Srinagar → Gulmarg → Pahalgam → Sonmarg",
    "category": "Leisure",
    "region": "Kashmir",
    "travelType": "Leisure",
    "audience": "Slow travel, couples, relaxed holiday",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / houseboat",
    "itinerarySummary": "D1 Arrival / start at Srinagar | D2 Move to Gulmarg | D3 Move to Pahalgam | D4 Move to Sonmarg | D5 Local sightseeing / buffer | D6 Departure / return",
    "originalItinerary": "Beautiful Kashmir 5N/6D",
    "pageTitle": "Kashmir Slow Escape | EscapeArc Kashmir Tour",
    "metaDescription": "Kashmir Slow Escape: 5N/6D EscapeArc kashmir experience covering Srinagar → Gulmarg → Pahalgam → Sonmarg. Built for slow travel, couples, relaxed holiday.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "kashmir-grand-circuit",
    "name": "Kashmir Grand Circuit",
    "type": "national",
    "duration": "6N/7D",
    "price": 8599,
    "priceLabel": "₹8,599–₹35,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Jammu → Katra → Patnitop → Srinagar → Gulmarg → Sonmarg → Pahalgam",
    "category": "Leisure",
    "region": "Kashmir",
    "travelType": "Leisure",
    "audience": "Long holiday, family travelers",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / houseboat",
    "itinerarySummary": "D1 Arrival / start at Jammu | D2 Sightseeing / transfer to Katra | D3 Sightseeing / transfer to Patnitop | D4 Sightseeing / transfer to Srinagar | D5 Local sightseeing / leisure | D6 Buffer / shopping / optional activities | D7 Departure",
    "originalItinerary": "Beautiful Kashmir 6N/7D",
    "pageTitle": "Kashmir Grand Circuit | EscapeArc Kashmir Tour",
    "metaDescription": "Kashmir Grand Circuit: 6N/7D EscapeArc kashmir experience covering Jammu → Katra → Patnitop → Srinagar → Gulmarg → Sonmarg → Pahalgam. Built for long holiday, family travelers.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "leh-starter-loop",
    "name": "Leh Starter Loop",
    "type": "national",
    "duration": "4N/5D",
    "price": 18200,
    "priceLabel": "₹18,200–₹38,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Leh → Sham Valley → Pangong → Monasteries → Khardung La",
    "category": "Leisure",
    "region": "Ladakh",
    "travelType": "Leisure",
    "audience": "Families, non-riders, premium sightseeing",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star / similar hotel",
    "itinerarySummary": "D1 Arrival / start at Leh | D2 Proceed to Sham Valley | D3 Proceed to Pangong | D4 Local sightseeing / leisure | D5 Departure / return",
    "originalItinerary": "Leh-Ladakh Car Tour 4N/5D",
    "pageTitle": "Leh Starter Loop | EscapeArc Ladakh Tour",
    "metaDescription": "Leh Starter Loop: 4N/5D EscapeArc ladakh experience covering Leh → Sham Valley → Pangong → Monasteries → Khardung La. Built for families, non-riders, premium sightseeing.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "leh-deep-dive",
    "name": "Leh Deep Dive",
    "type": "national",
    "duration": "6N/7D",
    "price": 18200,
    "priceLabel": "₹18,200–₹38,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Leh → Nubra → Pangong → Monasteries → departure",
    "category": "Leisure",
    "region": "Ladakh",
    "travelType": "Leisure",
    "audience": "Slow-paced Ladakh, families, couples",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star / similar hotel",
    "itinerarySummary": "D1 Arrival / start at Leh | D2 Sightseeing / transfer to Nubra | D3 Sightseeing / transfer to Pangong | D4 Sightseeing / transfer to Monasteries | D5 Local sightseeing / leisure | D6 Buffer / shopping / optional activities | D7 Departure",
    "originalItinerary": "Leh-Ladakh Car Tour 6N/7D",
    "pageTitle": "Leh Deep Dive | EscapeArc Ladakh Tour",
    "metaDescription": "Leh Deep Dive: 6N/7D EscapeArc ladakh experience covering Leh → Nubra → Pangong → Monasteries → departure. Built for slow-paced ladakh, families, couples.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "ladakh-ride-rewind",
    "name": "Ladakh Ride Rewind",
    "type": "national",
    "duration": "9N/10D",
    "price": 24500,
    "priceLabel": "₹24,500–₹65,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Manali → Keylong → Sarchu → Leh → Pangong → Khardung La → Srinagar",
    "category": "Biker Tour",
    "region": "Ladakh",
    "travelType": "Biker Tour",
    "audience": "Riders, creators, expedition audience",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star / similar hotel",
    "itinerarySummary": "D1 Start at Manali | D2 Travel to Keylong / sightseeing | D3 Travel to Sarchu / sightseeing | D4 Travel to Leh / sightseeing | D5 Travel to Pangong / sightseeing | D6 Travel to Khardung La / sightseeing | D7 Travel to Srinagar / sightseeing | D8 Local sightseeing / buffer | D9 Local sightseeing / buffer | D10 Departure / return",
    "originalItinerary": "Ladakh Bike Trip Manali-Srinagar",
    "pageTitle": "Ladakh Ride Rewind | EscapeArc Ladakh Tour",
    "metaDescription": "Ladakh Ride Rewind: 9N/10D EscapeArc ladakh experience covering Manali → Keylong → Sarchu → Leh → Pangong → Khardung La → Srinagar. Built for riders, creators, expedition audience.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "ladakh-apex-run",
    "name": "Ladakh Apex Run",
    "type": "national",
    "duration": "11D",
    "price": 18200,
    "priceLabel": "₹18,200–₹38,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Srinagar → Kargil → Leh → Nubra → Pangong → Hanle → Umling La → Leh → Jispa → Manali → Delhi",
    "category": "Leisure",
    "region": "Ladakh",
    "travelType": "Leisure",
    "audience": "Premium riders, extreme expedition",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star / similar hotel",
    "itinerarySummary": "D1 Start at Srinagar | D2 Travel to Kargil / sightseeing | D3 Travel to Leh / sightseeing | D4 Travel to Nubra / sightseeing | D5 Travel to Pangong / sightseeing | D6 Travel to Hanle / sightseeing | D7 Travel to Umling La / sightseeing | D8 Travel to Leh / sightseeing | D9 Travel to Jispa / sightseeing | D10 Travel to Manali / sightseeing | D11 Departure / return",
    "originalItinerary": "Ladakh Bike Trip Srinagar-Delhi via Umling La",
    "pageTitle": "Ladakh Apex Run | EscapeArc Ladakh Tour",
    "metaDescription": "Ladakh Apex Run: 11D EscapeArc ladakh experience covering Srinagar → Kargil → Leh → Nubra → Pangong → Hanle → Umling La → Leh → Jispa → Manali → Delhi. Built for premium riders, extreme expedition.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "ladakh-grand-loop",
    "name": "Ladakh Grand Loop",
    "type": "national",
    "duration": "12D",
    "price": 18200,
    "priceLabel": "₹18,200–₹38,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Delhi → Manali → Sarchu → Leh → Nubra → Pangong → Hanle → Umling La → Leh → Kargil → Srinagar",
    "category": "Leisure",
    "region": "Ladakh",
    "travelType": "Leisure",
    "audience": "Flagship expedition, premium riders",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star / similar hotel",
    "itinerarySummary": "D1 Start at Delhi | D2 Travel to Manali / sightseeing | D3 Travel to Sarchu / sightseeing | D4 Travel to Leh / sightseeing | D5 Travel to Nubra / sightseeing | D6 Travel to Pangong / sightseeing | D7 Travel to Hanle / sightseeing | D8 Travel to Umling La / sightseeing | D9 Travel to Leh / sightseeing | D10 Travel to Kargil / sightseeing | D11 Travel to Srinagar / sightseeing | D12 Departure / return",
    "originalItinerary": "Ladakh Bike Trip Delhi-Srinagar via Umling La",
    "pageTitle": "Ladakh Grand Loop | EscapeArc Ladakh Tour",
    "metaDescription": "Ladakh Grand Loop: 12D EscapeArc ladakh experience covering Delhi → Manali → Sarchu → Leh → Nubra → Pangong → Hanle → Umling La → Leh → Kargil → Srinagar. Built for flagship expedition, premium riders.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "ladakh-ultra-circuit",
    "name": "Ladakh Ultra Circuit",
    "type": "national",
    "duration": "10N/11D",
    "price": 18200,
    "priceLabel": "₹18,200–₹38,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Pune/Jammu → Leh → Nubra → Pangong → Tso Moriri → Sarchu → Jispa → Manali → Delhi",
    "category": "Biker Tour",
    "region": "Ladakh",
    "travelType": "Biker Tour",
    "audience": "Ultra expedition, limited batch",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star / similar hotel",
    "itinerarySummary": "D1 Start at Pune/Jammu | D2 Travel to Leh / sightseeing | D3 Travel to Nubra / sightseeing | D4 Travel to Pangong / sightseeing | D5 Travel to Tso Moriri / sightseeing | D6 Travel to Sarchu / sightseeing | D7 Travel to Jispa / sightseeing | D8 Travel to Manali / sightseeing | D9 Travel to Delhi / sightseeing | D10 Local sightseeing / buffer | D11 Departure / return",
    "originalItinerary": "Ladakh Extended Circuit",
    "pageTitle": "Ladakh Ultra Circuit | EscapeArc Ladakh Tour",
    "metaDescription": "Ladakh Ultra Circuit: 10N/11D EscapeArc ladakh experience covering Pune/Jammu → Leh → Nubra → Pangong → Tso Moriri → Sarchu → Jispa → Manali → Delhi. Built for ultra expedition, limited batch.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "himachal-classic-drift",
    "name": "Himachal Classic Drift",
    "type": "national",
    "duration": "5N/6D",
    "price": 7499,
    "priceLabel": "₹7,499–₹60,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Shimla → Kufri → Manali → Solang Valley → Kullu",
    "category": "Leisure",
    "region": "Himachal",
    "travelType": "Leisure",
    "audience": "Families, honeymooners, first hill trip",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star hotel / resort",
    "itinerarySummary": "D1 Arrival / start at Shimla | D2 Move to Kufri | D3 Move to Manali | D4 Move to Solang Valley | D5 Local sightseeing / buffer | D6 Departure / return",
    "originalItinerary": "Shimla-Manali-Solang-Kufri-Kullu",
    "pageTitle": "Himachal Classic Drift | EscapeArc Himachal Tour",
    "metaDescription": "Himachal Classic Drift: 5N/6D EscapeArc himachal experience covering Shimla → Kufri → Manali → Solang Valley → Kullu. Built for families, honeymooners, first hill trip.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "manali-magic-loop",
    "name": "Manali Magic Loop",
    "type": "national",
    "duration": "7D",
    "price": 7499,
    "priceLabel": "₹7,499–₹60,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Manali → Rohtang → Manikaran → Kullu",
    "category": "Leisure",
    "region": "Himachal",
    "travelType": "Leisure",
    "audience": "Short adventure + pilgrimage blend",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star hotel / resort",
    "itinerarySummary": "D1 Arrival / start at Manali | D2 Sightseeing / transfer to Rohtang | D3 Sightseeing / transfer to Manikaran | D4 Sightseeing / transfer to Kullu | D5 Local sightseeing / leisure | D6 Buffer / shopping / optional activities | D7 Departure",
    "originalItinerary": "Manali-Rohtang-Manikaran-Kullu",
    "pageTitle": "Manali Magic Loop | EscapeArc Himachal Tour",
    "metaDescription": "Manali Magic Loop: 7D EscapeArc himachal experience covering Manali → Rohtang → Manikaran → Kullu. Built for short adventure + pilgrimage blend.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "mini-manali-mood",
    "name": "Mini Manali Mood",
    "type": "national",
    "duration": "3N/4D",
    "price": 7499,
    "priceLabel": "₹7,499–₹60,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Manali → Rohtang → Kullu → Naggar",
    "category": "Leisure",
    "region": "Himachal",
    "travelType": "Leisure",
    "audience": "Weekend mountain break",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star hotel / resort",
    "itinerarySummary": "D1 Arrival / start at Manali | D2 Move to Rohtang / sightseeing | D3 Local excursion / leisure | D4 Departure / return",
    "originalItinerary": "Manali-Rohtang-Kullu-Naggar",
    "pageTitle": "Mini Manali Mood | EscapeArc Himachal Tour",
    "metaDescription": "Mini Manali Mood: 3N/4D EscapeArc himachal experience covering Manali → Rohtang → Kullu → Naggar. Built for weekend mountain break.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "himachal-hill-hop",
    "name": "Himachal Hill Hop",
    "type": "national",
    "duration": "3N/4D",
    "price": 7499,
    "priceLabel": "₹7,499–₹60,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Manali → Dharamshala → Dalhousie → Khajjiar",
    "category": "Leisure",
    "region": "Himachal",
    "travelType": "Leisure",
    "audience": "Scenic road-trip travelers",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star hotel / resort",
    "itinerarySummary": "D1 Arrival / start at Manali | D2 Move to Dharamshala / sightseeing | D3 Local excursion / leisure | D4 Departure / return",
    "originalItinerary": "Manali-Dharamshala-Dalhousie-Khajjiar",
    "pageTitle": "Himachal Hill Hop | EscapeArc Himachal Tour",
    "metaDescription": "Himachal Hill Hop: 3N/4D EscapeArc himachal experience covering Manali → Dharamshala → Dalhousie → Khajjiar. Built for scenic road-trip travelers.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "snowline-sprint",
    "name": "Snowline Sprint",
    "type": "national",
    "duration": "4N/5D",
    "price": 7499,
    "priceLabel": "₹7,499–₹60,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Shimla → Manali → Rohtang → Naggar → Solang",
    "category": "Leisure",
    "region": "Himachal",
    "travelType": "Leisure",
    "audience": "Classic hill circuit",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star hotel / resort",
    "itinerarySummary": "D1 Arrival / start at Shimla | D2 Proceed to Manali | D3 Proceed to Rohtang | D4 Local sightseeing / leisure | D5 Departure / return",
    "originalItinerary": "Shimla-Manali-Rohtang-Naggar-Solang",
    "pageTitle": "Snowline Sprint | EscapeArc Himachal Tour",
    "metaDescription": "Snowline Sprint: 4N/5D EscapeArc himachal experience covering Shimla → Manali → Rohtang → Naggar → Solang. Built for classic hill circuit.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "chamba-calm-circuit",
    "name": "Chamba Calm Circuit",
    "type": "national",
    "duration": "5N/6D",
    "price": 7499,
    "priceLabel": "₹7,499–₹60,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Dharamshala → Dalhousie → Khajjiar → Chamba",
    "category": "Leisure",
    "region": "Himachal",
    "travelType": "Leisure",
    "audience": "Quiet mountain holiday",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star hotel / resort",
    "itinerarySummary": "D1 Arrival / start at Dharamshala | D2 Move to Dalhousie | D3 Move to Khajjiar | D4 Move to Chamba | D5 Local sightseeing / buffer | D6 Departure / return",
    "originalItinerary": "Dharamshala-Dalhousie-Khajjiar-Chamba",
    "pageTitle": "Chamba Calm Circuit | EscapeArc Himachal Tour",
    "metaDescription": "Chamba Calm Circuit: 5N/6D EscapeArc himachal experience covering Dharamshala → Dalhousie → Khajjiar → Chamba. Built for quiet mountain holiday.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "queen-to-lake-trail",
    "name": "Queen-to-Lake Trail",
    "type": "national",
    "duration": "7N/8D",
    "price": 60000,
    "priceLabel": "₹60,000 (quoted)",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Mussoorie → Nainital → Jim Corbett → Delhi",
    "category": "Leisure",
    "region": "Uttarakhand",
    "travelType": "Leisure",
    "audience": "Families, wildlife, leisure",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star hotel / resort",
    "itinerarySummary": "D1 Arrival / start at Mussoorie | D2 Main sightseeing / transfer | D3 Main sightseeing / transfer | D4 Main sightseeing / transfer | D5 Main sightseeing / transfer | D6 Main sightseeing / transfer | D7 Leisure / shopping / optional | D8 Departure",
    "originalItinerary": "Mussoorie-Nainital-Corbett",
    "pageTitle": "Queen-to-Lake Trail | EscapeArc Uttarakhand Tour",
    "metaDescription": "Queen-to-Lake Trail: 7N/8D EscapeArc uttarakhand experience covering Mussoorie → Nainital → Jim Corbett → Delhi. Built for families, wildlife, leisure.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "sikkim-spark",
    "name": "Sikkim Spark",
    "type": "national",
    "duration": "6D",
    "price": 18800,
    "priceLabel": "₹18,800–₹29,750",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Gangtok → Tsomgo Lake → Baba Mandir → Lachung → Yumthang → Gangtok",
    "category": "Leisure",
    "region": "Sikkim",
    "travelType": "Leisure",
    "audience": "Nature, families, short mountain holiday",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / car-based",
    "itinerarySummary": "D1 Arrival / start at Gangtok | D2 Move to Tsomgo Lake | D3 Move to Baba Mandir | D4 Move to Lachung | D5 Local sightseeing / buffer | D6 Departure / return",
    "originalItinerary": "Sikkim Classic Tour",
    "pageTitle": "Sikkim Spark | EscapeArc Sikkim Tour",
    "metaDescription": "Sikkim Spark: 6D EscapeArc sikkim experience covering Gangtok → Tsomgo Lake → Baba Mandir → Lachung → Yumthang → Gangtok. Built for nature, families, short mountain holiday.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "sikkim-grand-north",
    "name": "Sikkim Grand North",
    "type": "national",
    "duration": "8D",
    "price": 18800,
    "priceLabel": "₹18,800–₹29,750",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Gangtok → Tsomgo Lake → Baba Mandir → Lachung → Yumthang → Pelling → Darjeeling",
    "category": "Leisure",
    "region": "Sikkim",
    "travelType": "Leisure",
    "audience": "Families, scenic travelers",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / car-based",
    "itinerarySummary": "D1 Arrival / start at Gangtok | D2 Main sightseeing / transfer | D3 Main sightseeing / transfer | D4 Main sightseeing / transfer | D5 Main sightseeing / transfer | D6 Main sightseeing / transfer | D7 Leisure / shopping / optional | D8 Departure",
    "originalItinerary": "Sikkim Extended Tour",
    "pageTitle": "Sikkim Grand North | EscapeArc Sikkim Tour",
    "metaDescription": "Sikkim Grand North: 8D EscapeArc sikkim experience covering Gangtok → Tsomgo Lake → Baba Mandir → Lachung → Yumthang → Pelling → Darjeeling. Built for families, scenic travelers.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "sikkim-ridge-+-river",
    "name": "Sikkim Ridge & River",
    "type": "national",
    "duration": "9D",
    "price": 18800,
    "priceLabel": "₹18,800–₹29,750",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Gangtok → Lachung → Yumthang → Pelling → Darjeeling",
    "category": "Leisure",
    "region": "Sikkim",
    "travelType": "Leisure",
    "audience": "Long scenic circuit",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / car-based",
    "itinerarySummary": "D1 Start at Gangtok | D2 Travel to Lachung / sightseeing | D3 Travel to Yumthang / sightseeing | D4 Travel to Pelling / sightseeing | D5 Travel to Darjeeling / sightseeing | D6 Local sightseeing / buffer | D7 Local sightseeing / buffer | D8 Local sightseeing / buffer | D9 Departure / return",
    "originalItinerary": "Sikkim + Darjeeling Tour",
    "pageTitle": "Sikkim Ridge & River | EscapeArc Sikkim Tour",
    "metaDescription": "Sikkim Ridge & River: 9D EscapeArc sikkim experience covering Gangtok → Lachung → Yumthang → Pelling → Darjeeling. Built for long scenic circuit.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "andaman-island-drift",
    "name": "Andaman Island Drift",
    "type": "national",
    "duration": "6N/7D",
    "price": 20000,
    "priceLabel": "₹20,000–₹51,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Port Blair → Havelock → Elephant Beach → Baratang → Diglipur → Ross & Smith → Port Blair",
    "category": "Leisure",
    "region": "Andaman",
    "travelType": "Leisure",
    "audience": "Families, island explorers",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / camp",
    "itinerarySummary": "D1 Arrival / start at Port Blair | D2 Sightseeing / transfer to Havelock | D3 Sightseeing / transfer to Elephant Beach | D4 Sightseeing / transfer to Baratang | D5 Local sightseeing / leisure | D6 Buffer / shopping / optional activities | D7 Departure",
    "originalItinerary": "Andaman Family Tour",
    "pageTitle": "Andaman Island Drift | EscapeArc Andaman Tour",
    "metaDescription": "Andaman Island Drift: 6N/7D EscapeArc andaman experience covering Port Blair → Havelock → Elephant Beach → Baratang → Diglipur → Ross & Smith → Port Blair. Built for families, island explorers.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "andaman-love-tide",
    "name": "Andaman Love Tide",
    "type": "national",
    "duration": "5N/6D",
    "price": 20000,
    "priceLabel": "₹20,000–₹51,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Port Blair → Havelock → Neil Island → Port Blair",
    "category": "Leisure",
    "region": "Andaman",
    "travelType": "Leisure",
    "audience": "Couples, honeymooners",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / camp",
    "itinerarySummary": "D1 Arrival / start at Port Blair | D2 Move to Havelock | D3 Move to Neil Island | D4 Move to Port Blair | D5 Local sightseeing / buffer | D6 Departure / return",
    "originalItinerary": "Andaman Honeymoon Tour",
    "pageTitle": "Andaman Love Tide | EscapeArc Andaman Tour",
    "metaDescription": "Andaman Love Tide: 5N/6D EscapeArc andaman experience covering Port Blair → Havelock → Neil Island → Port Blair. Built for couples, honeymooners.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "goa-shoreline-drift",
    "name": "Goa Shoreline Drift",
    "type": "national",
    "duration": "3N/4D",
    "price": 4600,
    "priceLabel": "₹4,600–₹32,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Goa → North Goa → South Goa → Goa",
    "category": "Leisure",
    "region": "Goa",
    "travelType": "Leisure",
    "audience": "Beach leisure, short breaks",
    "positioning": "SEO-ready travel product",
    "stayType": "Beach resort / hotel",
    "itinerarySummary": "D1 Arrival / start at Goa | D2 Move to North Goa / sightseeing | D3 Local excursion / leisure | D4 Departure / return",
    "originalItinerary": "Goa Beach Holiday",
    "pageTitle": "Goa Shoreline Drift | EscapeArc Goa Tour",
    "metaDescription": "Goa Shoreline Drift: 3N/4D EscapeArc goa experience covering Goa → North Goa → South Goa → Goa. Built for beach leisure, short breaks.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "goa-crew-escape",
    "name": "Goa Crew Escape",
    "type": "national",
    "duration": "3N/4D",
    "price": 4600,
    "priceLabel": "₹4,600–₹32,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Goa → North Goa → South Goa → Goa",
    "category": "Leisure",
    "region": "Goa",
    "travelType": "Leisure",
    "audience": "Friends, college groups",
    "positioning": "SEO-ready travel product",
    "stayType": "Beach resort / hotel",
    "itinerarySummary": "D1 Arrival / start at Goa | D2 Move to North Goa / sightseeing | D3 Local excursion / leisure | D4 Departure / return",
    "originalItinerary": "Goa Group Tour",
    "pageTitle": "Goa Crew Escape | EscapeArc Goa Tour",
    "metaDescription": "Goa Crew Escape: 3N/4D EscapeArc goa experience covering Goa → North Goa → South Goa → Goa. Built for friends, college groups.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "kerala-backwater-bloom",
    "name": "Kerala Backwater Bloom",
    "type": "national",
    "duration": "4N/5D",
    "price": 14300,
    "priceLabel": "₹14,300–₹35,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Cochin → Munnar → Alleppey → Thekkady",
    "category": "Leisure",
    "region": "Kerala",
    "travelType": "Leisure",
    "audience": "Families, first Kerala trip",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / houseboat",
    "itinerarySummary": "D1 Arrival / start at Cochin | D2 Proceed to Munnar | D3 Proceed to Alleppey | D4 Local sightseeing / leisure | D5 Departure / return",
    "originalItinerary": "Kerala Family Tour 4N/5D",
    "pageTitle": "Kerala Backwater Bloom | EscapeArc Kerala Tour",
    "metaDescription": "Kerala Backwater Bloom: 4N/5D EscapeArc kerala experience covering Cochin → Munnar → Alleppey → Thekkady. Built for families, first kerala trip.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "kerala-classic-coast-+-hills",
    "name": "Kerala Classic Coast & Hills",
    "type": "national",
    "duration": "6N/7D",
    "price": 14300,
    "priceLabel": "₹14,300–₹35,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Cochin → Munnar → Alleppey → Thekkady → Kovalam",
    "category": "Leisure",
    "region": "Kerala",
    "travelType": "Leisure",
    "audience": "Longer family holiday",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / houseboat",
    "itinerarySummary": "D1 Arrival / start at Cochin | D2 Sightseeing / transfer to Munnar | D3 Sightseeing / transfer to Alleppey | D4 Sightseeing / transfer to Thekkady | D5 Local sightseeing / leisure | D6 Buffer / shopping / optional activities | D7 Departure",
    "originalItinerary": "Kerala Family Tour 6N/7D",
    "pageTitle": "Kerala Classic Coast & Hills | EscapeArc Kerala Tour",
    "metaDescription": "Kerala Classic Coast & Hills: 6N/7D EscapeArc kerala experience covering Cochin → Munnar → Alleppey → Thekkady → Kovalam. Built for longer family holiday.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "kerala-long-escape",
    "name": "Kerala Long Escape",
    "type": "national",
    "duration": "8N/9D",
    "price": 14300,
    "priceLabel": "₹14,300–₹35,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Cochin → Munnar → Alleppey → Thekkady → Kumarakom",
    "category": "Leisure",
    "region": "Kerala",
    "travelType": "Leisure",
    "audience": "Slow travel, premium leisure",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / houseboat",
    "itinerarySummary": "D1 Start at Cochin | D2 Travel to Munnar / sightseeing | D3 Travel to Alleppey / sightseeing | D4 Travel to Thekkady / sightseeing | D5 Travel to Kumarakom / sightseeing | D6 Local sightseeing / buffer | D7 Local sightseeing / buffer | D8 Local sightseeing / buffer | D9 Departure / return",
    "originalItinerary": "Kerala Family Tour 8N/9D",
    "pageTitle": "Kerala Long Escape | EscapeArc Kerala Tour",
    "metaDescription": "Kerala Long Escape: 8N/9D EscapeArc kerala experience covering Cochin → Munnar → Alleppey → Thekkady → Kumarakom. Built for slow travel, premium leisure.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "kerala-south-loop",
    "name": "Kerala South Loop",
    "type": "national",
    "duration": "9N/10D",
    "price": 14300,
    "priceLabel": "₹14,300–₹35,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Akola → Hyderabad → Trivandrum → Kovalam → Kanyakumari → Alleppey/Kumarakom → Thekkady → Munnar → Cochin",
    "category": "Leisure",
    "region": "Kerala",
    "travelType": "Leisure",
    "audience": "Long South India family tour",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / houseboat",
    "itinerarySummary": "D1 Start at Akola | D2 Travel to Hyderabad / sightseeing | D3 Travel to Trivandrum / sightseeing | D4 Travel to Kovalam / sightseeing | D5 Travel to Kanyakumari / sightseeing | D6 Travel to Alleppey/Kumarakom / sightseeing | D7 Travel to Thekkady / sightseeing | D8 Travel to Munnar / sightseeing | D9 Travel to Cochin / sightseeing | D10 Departure / return",
    "originalItinerary": "Kerala Family Tour 9N/10D",
    "pageTitle": "Kerala South Loop | EscapeArc Kerala Tour",
    "metaDescription": "Kerala South Loop: 9N/10D EscapeArc kerala experience covering Akola → Hyderabad → Trivandrum → Kovalam → Kanyakumari → Alleppey/Kumarakom → Thekkady → Munnar → Cochin. Built for long south india family tour.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "kerala-honeymoon-glow",
    "name": "Kerala Honeymoon Glow",
    "type": "national",
    "duration": "5D",
    "price": 14300,
    "priceLabel": "₹14,300–₹35,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Cochin → Munnar → Alleppey",
    "category": "Honeymoon",
    "region": "Kerala",
    "travelType": "Honeymoon",
    "audience": "Couples",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / houseboat",
    "itinerarySummary": "D1 Arrival / start at Cochin | D2 Proceed to Munnar | D3 Proceed to Alleppey | D4 Local sightseeing / leisure | D5 Departure / return",
    "originalItinerary": "Kerala Honeymoon Tour 5D",
    "pageTitle": "Kerala Honeymoon Glow | EscapeArc Kerala Tour",
    "metaDescription": "Kerala Honeymoon Glow: 5D EscapeArc kerala experience covering Cochin → Munnar → Alleppey. Built for couples.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "kerala-couple-coastline",
    "name": "Kerala Couple Coastline",
    "type": "national",
    "duration": "6D",
    "price": 14300,
    "priceLabel": "₹14,300–₹35,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Munnar → Alleppey → Kovalam → Trivandrum",
    "category": "Leisure",
    "region": "Kerala",
    "travelType": "Leisure",
    "audience": "Couples",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / houseboat",
    "itinerarySummary": "D1 Arrival / start at Munnar | D2 Move to Alleppey | D3 Move to Kovalam | D4 Move to Trivandrum | D5 Local sightseeing / buffer | D6 Departure / return",
    "originalItinerary": "Kerala Honeymoon Tour 6D Variant 1",
    "pageTitle": "Kerala Couple Coastline | EscapeArc Kerala Tour",
    "metaDescription": "Kerala Couple Coastline: 6D EscapeArc kerala experience covering Munnar → Alleppey → Kovalam → Trivandrum. Built for couples.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "kerala-couple-pulse",
    "name": "Kerala Couple Pulse",
    "type": "national",
    "duration": "6D",
    "price": 14300,
    "priceLabel": "₹14,300–₹35,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Cochin → Munnar → Alleppey",
    "category": "Leisure",
    "region": "Kerala",
    "travelType": "Leisure",
    "audience": "Couples, quick honeymoon",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / houseboat",
    "itinerarySummary": "D1 Arrival / check-in | D2 Main sightseeing | D3 Secondary excursion | D4 Leisure / transfer | D5 Local sightseeing / buffer | D6 Departure",
    "originalItinerary": "Kerala Honeymoon Tour 6D Variant 2",
    "pageTitle": "Kerala Couple Pulse | EscapeArc Kerala Tour",
    "metaDescription": "Kerala Couple Pulse: 6D EscapeArc kerala experience covering Cochin → Munnar → Alleppey. Built for couples, quick honeymoon.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "kerala-luxe-love-loop",
    "name": "Kerala Luxe Love Loop",
    "type": "national",
    "duration": "6D",
    "price": 14300,
    "priceLabel": "₹14,300–₹35,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Cochin → Munnar → Alleppey → Thekkady → Kumarakom",
    "category": "Leisure",
    "region": "Kerala",
    "travelType": "Leisure",
    "audience": "Premium couples",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / houseboat",
    "itinerarySummary": "D1 Arrival / start at Cochin | D2 Move to Munnar | D3 Move to Alleppey | D4 Move to Thekkady | D5 Local sightseeing / buffer | D6 Departure / return",
    "originalItinerary": "Kerala Honeymoon Tour 6D Variant 3",
    "pageTitle": "Kerala Luxe Love Loop | EscapeArc Kerala Tour",
    "metaDescription": "Kerala Luxe Love Loop: 6D EscapeArc kerala experience covering Cochin → Munnar → Alleppey → Thekkady → Kumarakom. Built for premium couples.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "kerala-grand-honeymoon-arc",
    "name": "Kerala Grand Honeymoon Arc",
    "type": "national",
    "duration": "12D",
    "price": 14300,
    "priceLabel": "₹14,300–₹35,800",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Cochin → Munnar → Alleppey → Thekkady → Madurai",
    "category": "Honeymoon",
    "region": "Kerala",
    "travelType": "Honeymoon",
    "audience": "Long honeymoon / premium",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / houseboat",
    "itinerarySummary": "D1 Start at Cochin | D2 Travel to Munnar / sightseeing | D3 Travel to Alleppey / sightseeing | D4 Travel to Thekkady / sightseeing | D5 Travel to Madurai / sightseeing | D6 Local sightseeing / buffer | D7 Local sightseeing / buffer | D8 Local sightseeing / buffer | D9 Local sightseeing / buffer | D10 Local sightseeing / buffer | D11 Local sightseeing / buffer | D12 Departure / return",
    "originalItinerary": "Kerala Honeymoon Tour 12D",
    "pageTitle": "Kerala Grand Honeymoon Arc | EscapeArc Kerala Tour",
    "metaDescription": "Kerala Grand Honeymoon Arc: 12D EscapeArc kerala experience covering Cochin → Munnar → Alleppey → Thekkady → Madurai. Built for long honeymoon / premium.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "royal-rajasthan-run",
    "name": "Royal Rajasthan Run",
    "type": "national",
    "duration": "8N/9D",
    "price": 7400,
    "priceLabel": "₹7,400–₹34,500",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Jaipur → Ajmer → Pushkar → Jaisalmer → Jodhpur → Udaipur → Mount Abu",
    "category": "Leisure",
    "region": "Rajasthan & Gujarat",
    "travelType": "Leisure",
    "audience": "Culture, family, heritage",
    "positioning": "SEO-ready travel product",
    "stayType": "Budget / 3-star hotel / camp",
    "itinerarySummary": "D1 Start at Jaipur | D2 Travel to Ajmer / sightseeing | D3 Travel to Pushkar / sightseeing | D4 Travel to Jaisalmer / sightseeing | D5 Travel to Jodhpur / sightseeing | D6 Travel to Udaipur / sightseeing | D7 Travel to Mount Abu / sightseeing | D8 Local sightseeing / buffer | D9 Departure / return",
    "originalItinerary": "Rajasthan Tour",
    "pageTitle": "Royal Rajasthan Run | EscapeArc Rajasthan & Gujarat Tour",
    "metaDescription": "Royal Rajasthan Run: 8N/9D EscapeArc rajasthan & gujarat experience covering Jaipur → Ajmer → Pushkar → Jaisalmer → Jodhpur → Udaipur → Mount Abu. Built for culture, family, heritage.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "rajasthan-campus-circuit",
    "name": "Rajasthan Campus Circuit",
    "type": "national",
    "duration": "7N/8D",
    "price": 7400,
    "priceLabel": "₹7,400–₹34,500",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Badnera → Mount Abu → Udaipur → Jaipur → Delhi → Amravati",
    "category": "Leisure",
    "region": "Rajasthan & Gujarat",
    "travelType": "Leisure",
    "audience": "Student / industrial visits",
    "positioning": "SEO-ready travel product",
    "stayType": "Budget / 3-star hotel / camp",
    "itinerarySummary": "D1 Arrival / start at Badnera | D2 Main sightseeing / transfer | D3 Main sightseeing / transfer | D4 Main sightseeing / transfer | D5 Main sightseeing / transfer | D6 Main sightseeing / transfer | D7 Leisure / shopping / optional | D8 Departure",
    "originalItinerary": "Jaipur-Udaipur-Mount Abu Industrial Visit",
    "pageTitle": "Rajasthan Campus Circuit | EscapeArc Rajasthan & Gujarat Tour",
    "metaDescription": "Rajasthan Campus Circuit: 7N/8D EscapeArc rajasthan & gujarat experience covering Badnera → Mount Abu → Udaipur → Jaipur → Delhi → Amravati. Built for student / industrial visits.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "mount-abu-campus-loop",
    "name": "Mount Abu Campus Loop",
    "type": "national",
    "duration": "7N/8D",
    "price": 7400,
    "priceLabel": "₹7,400–₹34,500",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Shegaon/Malkapur → Ahmedabad → Mount Abu → Ahmedabad → Shegaon",
    "category": "Leisure",
    "region": "Rajasthan & Gujarat",
    "travelType": "Leisure",
    "audience": "Student / industrial visits",
    "positioning": "SEO-ready travel product",
    "stayType": "Budget / 3-star hotel / camp",
    "itinerarySummary": "D1 Arrival / start at Shegaon/Malkapur | D2 Main sightseeing / transfer | D3 Main sightseeing / transfer | D4 Main sightseeing / transfer | D5 Main sightseeing / transfer | D6 Main sightseeing / transfer | D7 Leisure / shopping / optional | D8 Departure",
    "originalItinerary": "Ahmedabad-Mount Abu Industrial Visit",
    "pageTitle": "Mount Abu Campus Loop | EscapeArc Rajasthan & Gujarat Tour",
    "metaDescription": "Mount Abu Campus Loop: 7N/8D EscapeArc rajasthan & gujarat experience covering Shegaon/Malkapur → Ahmedabad → Mount Abu → Ahmedabad → Shegaon. Built for student / industrial visits.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "gujarat-sacred-circuit",
    "name": "Gujarat Sacred Circuit",
    "type": "national",
    "duration": "6N/7D",
    "price": 7400,
    "priceLabel": "₹7,400–₹34,500",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Ahmedabad → Jamnagar → Dwarka → Porbandar → Somnath → Rajkot → Ahmedabad",
    "category": "Leisure",
    "region": "Rajasthan & Gujarat",
    "travelType": "Leisure",
    "audience": "Religious + family",
    "positioning": "SEO-ready travel product",
    "stayType": "Budget / 3-star hotel / camp",
    "itinerarySummary": "D1 Arrival / start at Ahmedabad | D2 Sightseeing / transfer to Jamnagar | D3 Sightseeing / transfer to Dwarka | D4 Sightseeing / transfer to Porbandar | D5 Local sightseeing / leisure | D6 Buffer / shopping / optional activities | D7 Departure",
    "originalItinerary": "Dwarka-Somnath Tour",
    "pageTitle": "Gujarat Sacred Circuit | EscapeArc Rajasthan & Gujarat Tour",
    "metaDescription": "Gujarat Sacred Circuit: 6N/7D EscapeArc rajasthan & gujarat experience covering Ahmedabad → Jamnagar → Dwarka → Porbandar → Somnath → Rajkot → Ahmedabad. Built for religious + family.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "central-india-heritage-loop",
    "name": "Central India Heritage Loop",
    "type": "national",
    "duration": "6D",
    "price": 7400,
    "priceLabel": "₹7,400–₹34,500",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Shegaon → Indore → Jaipur → Udaipur → Akola",
    "category": "Leisure",
    "region": "Rajasthan & Gujarat",
    "travelType": "Leisure",
    "audience": "Heritage leisure",
    "positioning": "SEO-ready travel product",
    "stayType": "Budget / 3-star hotel / camp",
    "itinerarySummary": "D1 Arrival / start at Shegaon | D2 Move to Indore | D3 Move to Jaipur | D4 Move to Udaipur | D5 Local sightseeing / buffer | D6 Departure / return",
    "originalItinerary": "Indore-Jaipur-Udaipur Tour",
    "pageTitle": "Central India Heritage Loop | EscapeArc Rajasthan & Gujarat Tour",
    "metaDescription": "Central India Heritage Loop: 6D EscapeArc rajasthan & gujarat experience covering Shegaon → Indore → Jaipur → Udaipur → Akola. Built for heritage leisure.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "hyderabad-bright-line",
    "name": "Hyderabad Bright Line",
    "type": "national",
    "duration": "4N/5D",
    "price": 5600,
    "priceLabel": "₹5,600–₹9,999",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Badnera → Hyderabad → Ramoji Film City → return",
    "category": "Leisure",
    "region": "South India",
    "travelType": "Leisure",
    "audience": "Students, industrial visit",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / car-based",
    "itinerarySummary": "D1 Arrival / start at Badnera | D2 Proceed to Hyderabad | D3 Proceed to Ramoji Film City | D4 Local sightseeing / leisure | D5 Departure / return",
    "originalItinerary": "Hyderabad Student Tour Badnera",
    "pageTitle": "Hyderabad Bright Line | EscapeArc South India Tour",
    "metaDescription": "Hyderabad Bright Line: 4N/5D EscapeArc south india experience covering Badnera → Hyderabad → Ramoji Film City → return. Built for students, industrial visit.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "hyderabad-city-quest",
    "name": "Hyderabad City Quest",
    "type": "national",
    "duration": "4N/5D",
    "price": 5600,
    "priceLabel": "₹5,600–₹9,999",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Shegaon → Hyderabad → Ramoji Film City → return",
    "category": "Leisure",
    "region": "South India",
    "travelType": "Leisure",
    "audience": "Students, industrial visit",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / car-based",
    "itinerarySummary": "D1 Arrival / start at Shegaon | D2 Proceed to Hyderabad | D3 Proceed to Ramoji Film City | D4 Local sightseeing / leisure | D5 Departure / return",
    "originalItinerary": "Hyderabad Student Tour Shegaon",
    "pageTitle": "Hyderabad City Quest | EscapeArc South India Tour",
    "metaDescription": "Hyderabad City Quest: 4N/5D EscapeArc south india experience covering Shegaon → Hyderabad → Ramoji Film City → return. Built for students, industrial visit.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "southern-hills-circuit",
    "name": "Southern Hills Circuit",
    "type": "national",
    "duration": "7D",
    "price": 5600,
    "priceLabel": "₹5,600–₹9,999",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Bangalore → Mysore → Ooty → Kodaikanal → return",
    "category": "Leisure",
    "region": "South India",
    "travelType": "Leisure",
    "audience": "Families, scenic holiday",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / car-based",
    "itinerarySummary": "D1 Arrival / start at Bangalore | D2 Sightseeing / transfer to Mysore | D3 Sightseeing / transfer to Ooty | D4 Sightseeing / transfer to Kodaikanal | D5 Local sightseeing / leisure | D6 Buffer / shopping / optional activities | D7 Departure",
    "originalItinerary": "Bangalore-Mysore-Ooty-Kodaikanal Tour",
    "pageTitle": "Southern Hills Circuit | EscapeArc South India Tour",
    "metaDescription": "Southern Hills Circuit: 7D EscapeArc south india experience covering Bangalore → Mysore → Ooty → Kodaikanal → return. Built for families, scenic holiday.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "konkan-coast-glide",
    "name": "Konkan Coast Glide",
    "type": "national",
    "duration": "5N/6D",
    "price": 5600,
    "priceLabel": "₹5,600–₹9,999",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Akola → Pune → Tarkarli → Pune → Akola",
    "category": "Leisure",
    "region": "South India",
    "travelType": "Leisure",
    "audience": "Beach leisure",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / car-based",
    "itinerarySummary": "D1 Arrival / start at Akola | D2 Move to Pune | D3 Move to Tarkarli | D4 Move to Pune | D5 Local sightseeing / buffer | D6 Departure / return",
    "originalItinerary": "Tarkarli Tour",
    "pageTitle": "Konkan Coast Glide | EscapeArc South India Tour",
    "metaDescription": "Konkan Coast Glide: 5N/6D EscapeArc south india experience covering Akola → Pune → Tarkarli → Pune → Akola. Built for beach leisure.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "coorg-calm-trails",
    "name": "Coorg Calm Trails",
    "type": "national",
    "duration": "2N/3D",
    "price": 5600,
    "priceLabel": "₹5,600–₹9,999",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Bangalore → Coorg → Madikeri → Bangalore",
    "category": "Leisure",
    "region": "South India",
    "travelType": "Leisure",
    "audience": "Short scenic break",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / resort / car-based",
    "itinerarySummary": "D1 Arrival / start at Bangalore | D2 Move to Coorg / sightseeing | D3 Local excursion / leisure",
    "originalItinerary": "Coorg Tour",
    "pageTitle": "Coorg Calm Trails | EscapeArc South India Tour",
    "metaDescription": "Coorg Calm Trails: 2N/3D EscapeArc south india experience covering Bangalore → Coorg → Madikeri → Bangalore. Built for short scenic break.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "meghalaya-waterfall-rush",
    "name": "Meghalaya Waterfall Rush",
    "type": "national",
    "duration": "4N/5D",
    "price": 23500,
    "priceLabel": "₹23,500–₹32,500",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Shillong → Sohra/Cherrapunji → Dawki → Mawlynnong → Shillong",
    "category": "Backpacking",
    "region": "Meghalaya",
    "travelType": "Backpacking",
    "audience": "Monsoon lovers, youth, families",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / camp",
    "itinerarySummary": "D1 Arrival / start at Shillong | D2 Proceed to Sohra/Cherrapunji | D3 Proceed to Dawki | D4 Local sightseeing / leisure | D5 Departure / return",
    "originalItinerary": "Shillong-Cherrapunji-Dawki",
    "pageTitle": "Meghalaya Waterfall Rush | EscapeArc Meghalaya Tour",
    "metaDescription": "Meghalaya Waterfall Rush: 4N/5D EscapeArc meghalaya experience covering Shillong → Sohra/Cherrapunji → Dawki → Mawlynnong → Shillong. Built for monsoon lovers, youth, families.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "meghalaya-monsoon-maze",
    "name": "Meghalaya Monsoon Maze",
    "type": "national",
    "duration": "6N/7D",
    "price": 23500,
    "priceLabel": "₹23,500–₹32,500",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Shillong → Sohra → Dawki → Mawlynnong → Jowai → Shillong",
    "category": "Backpacking",
    "region": "Meghalaya",
    "travelType": "Backpacking",
    "audience": "Scenic + culture",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / camp",
    "itinerarySummary": "D1 Arrival / start at Shillong | D2 Sightseeing / transfer to Sohra | D3 Sightseeing / transfer to Dawki | D4 Sightseeing / transfer to Mawlynnong | D5 Local sightseeing / leisure | D6 Buffer / shopping / optional activities | D7 Departure",
    "originalItinerary": "Meghalaya Extended Circuit",
    "pageTitle": "Meghalaya Monsoon Maze | EscapeArc Meghalaya Tour",
    "metaDescription": "Meghalaya Monsoon Maze: 6N/7D EscapeArc meghalaya experience covering Shillong → Sohra → Dawki → Mawlynnong → Jowai → Shillong. Built for scenic + culture.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "tawang-dawn-trail",
    "name": "Tawang Dawn Trail",
    "type": "national",
    "duration": "7N/8D",
    "price": 24300,
    "priceLabel": "₹24,300–₹60,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Bhalukpong → Dirang → Tawang → Bomdila → Guwahati exit",
    "category": "Backpacking",
    "region": "Arunachal Pradesh",
    "travelType": "Backpacking",
    "audience": "Frontier explorers",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / homestay",
    "itinerarySummary": "D1 Arrival / start at Bhalukpong | D2 Main sightseeing / transfer | D3 Main sightseeing / transfer | D4 Main sightseeing / transfer | D5 Main sightseeing / transfer | D6 Main sightseeing / transfer | D7 Leisure / shopping / optional | D8 Departure",
    "originalItinerary": "Tawang Circuit",
    "pageTitle": "Tawang Dawn Trail | EscapeArc Arunachal Pradesh Tour",
    "metaDescription": "Tawang Dawn Trail: 7N/8D EscapeArc arunachal pradesh experience covering Bhalukpong → Dirang → Tawang → Bomdila → Guwahati exit. Built for frontier explorers.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "mechuka-frontier-drift",
    "name": "Mechuka Frontier Drift",
    "type": "national",
    "duration": "9N/10D",
    "price": 24300,
    "priceLabel": "₹24,300–₹60,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Itanagar/Guwahati → Ziro/Itanagar → Aalo → Mechuka → return",
    "category": "Backpacking",
    "region": "Arunachal Pradesh",
    "travelType": "Backpacking",
    "audience": "Hardcore explorers",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / homestay",
    "itinerarySummary": "D1 Start at Itanagar/Guwahati | D2 Travel to Ziro/Itanagar / sightseeing | D3 Travel to Aalo / sightseeing | D4 Travel to Mechuka / sightseeing | D5 Travel to return / sightseeing | D6 Local sightseeing / buffer | D7 Local sightseeing / buffer | D8 Local sightseeing / buffer | D9 Local sightseeing / buffer | D10 Departure / return",
    "originalItinerary": "Mechuka Expedition",
    "pageTitle": "Mechuka Frontier Drift | EscapeArc Arunachal Pradesh Tour",
    "metaDescription": "Mechuka Frontier Drift: 9N/10D EscapeArc arunachal pradesh experience covering Itanagar/Guwahati → Ziro/Itanagar → Aalo → Mechuka → return. Built for hardcore explorers.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "spiti-cold-desert-loop",
    "name": "Spiti Cold Desert Loop",
    "type": "national",
    "duration": "8N/9D",
    "price": 23500,
    "priceLabel": "₹23,500–₹42,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Shimla → Chitkul → Kalpa → Tabo → Dhankar → Kaza → Pin Valley → Chandratal → Manali",
    "category": "Backpacking",
    "region": "Spiti",
    "travelType": "Backpacking",
    "audience": "Riders, explorers",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / camp / homestay",
    "itinerarySummary": "D1 Start at Shimla | D2 Travel to Chitkul / sightseeing | D3 Travel to Kalpa / sightseeing | D4 Travel to Tabo / sightseeing | D5 Travel to Dhankar / sightseeing | D6 Travel to Kaza / sightseeing | D7 Travel to Pin Valley / sightseeing | D8 Travel to Chandratal / sightseeing | D9 Departure / return",
    "originalItinerary": "Spiti Core Circuit",
    "pageTitle": "Spiti Cold Desert Loop | EscapeArc Spiti Tour",
    "metaDescription": "Spiti Cold Desert Loop: 8N/9D EscapeArc spiti experience covering Shimla → Chitkul → Kalpa → Tabo → Dhankar → Kaza → Pin Valley → Chandratal → Manali. Built for riders, explorers.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "spiti-quickfreeze-trail",
    "name": "Spiti Quickfreeze Trail",
    "type": "national",
    "duration": "6N/7D",
    "price": 23500,
    "priceLabel": "₹23,500–₹42,000",
    "totalSeats": 25,
    "bookedSeats": 0,
    "route": "Shimla → Chitkul → Kalpa → Tabo → Kaza → Manali",
    "category": "Backpacking",
    "region": "Spiti",
    "travelType": "Backpacking",
    "audience": "Shorter premium Spiti",
    "positioning": "SEO-ready travel product",
    "stayType": "Hotel / camp / homestay",
    "itinerarySummary": "D1 Arrival / start at Shimla | D2 Sightseeing / transfer to Chitkul | D3 Sightseeing / transfer to Kalpa | D4 Sightseeing / transfer to Tabo | D5 Local sightseeing / leisure | D6 Buffer / shopping / optional activities | D7 Departure",
    "originalItinerary": "Spiti Short Premium",
    "pageTitle": "Spiti Quickfreeze Trail | EscapeArc Spiti Tour",
    "metaDescription": "Spiti Quickfreeze Trail: 6N/7D EscapeArc spiti experience covering Shimla → Chitkul → Kalpa → Tabo → Kaza → Manali. Built for shorter premium spiti.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "nepal-peak-pulse",
    "name": "Nepal Peak Pulse",
    "type": "international",
    "duration": "6N/7D",
    "price": 28650,
    "priceLabel": "₹28,650–₹2,20,000",
    "totalSeats": 16,
    "bookedSeats": 0,
    "route": "Kathmandu → Pokhara → Chitwan → Kathmandu",
    "category": "International",
    "region": "International",
    "travelType": "International",
    "audience": "Families, Himalayan leisure",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star / similar hotel",
    "itinerarySummary": "D1 Arrival / start at Kathmandu | D2 Sightseeing / transfer to Pokhara | D3 Sightseeing / transfer to Chitwan | D4 Sightseeing / transfer to Kathmandu | D5 Local sightseeing / leisure | D6 Buffer / shopping / optional activities | D7 Departure",
    "originalItinerary": "Nepal Classic Circuit",
    "pageTitle": "Nepal Peak Pulse | EscapeArc International Tour",
    "metaDescription": "Nepal Peak Pulse: 6N/7D EscapeArc international experience covering Kathmandu → Pokhara → Chitwan → Kathmandu. Built for families, himalayan leisure.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "bhutan-calm-kingdom",
    "name": "Bhutan Calm Kingdom",
    "type": "international",
    "duration": "6N/7D",
    "price": 28650,
    "priceLabel": "₹28,650–₹2,20,000",
    "totalSeats": 16,
    "bookedSeats": 0,
    "route": "Paro → Thimphu → Punakha → Paro",
    "category": "International",
    "region": "International",
    "travelType": "International",
    "audience": "Premium cultural travel",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star / similar hotel",
    "itinerarySummary": "D1 Arrival / start at Paro | D2 Sightseeing / transfer to Thimphu | D3 Sightseeing / transfer to Punakha | D4 Sightseeing / transfer to Paro | D5 Local sightseeing / leisure | D6 Buffer / shopping / optional activities | D7 Departure",
    "originalItinerary": "Bhutan Core Circuit",
    "pageTitle": "Bhutan Calm Kingdom | EscapeArc International Tour",
    "metaDescription": "Bhutan Calm Kingdom: 6N/7D EscapeArc international experience covering Paro → Thimphu → Punakha → Paro. Built for premium cultural travel.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "vietnam-river-to-ridge",
    "name": "Vietnam River-to-Ridge",
    "type": "international",
    "duration": "8N/9D",
    "price": 28650,
    "priceLabel": "₹28,650–₹2,20,000",
    "totalSeats": 16,
    "bookedSeats": 0,
    "route": "Hanoi → Halong → Sapa/Ninh Binh → Hoi An → Hue → Ho Chi Minh City",
    "category": "International",
    "region": "International",
    "travelType": "International",
    "audience": "Youth, content travelers",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star / similar hotel",
    "itinerarySummary": "D1 Start at Hanoi | D2 Travel to Halong / sightseeing | D3 Travel to Sapa/Ninh Binh / sightseeing | D4 Travel to Hoi An / sightseeing | D5 Travel to Hue / sightseeing | D6 Travel to Ho Chi Minh City / sightseeing | D7 Local sightseeing / buffer | D8 Local sightseeing / buffer | D9 Departure / return",
    "originalItinerary": "Vietnam Scenic Circuit",
    "pageTitle": "Vietnam River-to-Ridge | EscapeArc International Tour",
    "metaDescription": "Vietnam River-to-Ridge: 8N/9D EscapeArc international experience covering Hanoi → Halong → Sapa/Ninh Binh → Hoi An → Hue → Ho Chi Minh City. Built for youth, content travelers.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "sri-lanka-wave-+-temple-run",
    "name": "Sri Lanka Wave & Temple Run",
    "type": "international",
    "duration": "7N/8D",
    "price": 28650,
    "priceLabel": "₹28,650–₹2,20,000",
    "totalSeats": 16,
    "bookedSeats": 0,
    "route": "Colombo → Kandy → Ella/Nuwara Eliya → Galle → Colombo",
    "category": "International",
    "region": "International",
    "travelType": "International",
    "audience": "Families, couples",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star / similar hotel",
    "itinerarySummary": "D1 Arrival / start at Colombo | D2 Main sightseeing / transfer | D3 Main sightseeing / transfer | D4 Main sightseeing / transfer | D5 Main sightseeing / transfer | D6 Main sightseeing / transfer | D7 Leisure / shopping / optional | D8 Departure",
    "originalItinerary": "Sri Lanka Classic Circuit",
    "pageTitle": "Sri Lanka Wave & Temple Run | EscapeArc International Tour",
    "metaDescription": "Sri Lanka Wave & Temple Run: 7N/8D EscapeArc international experience covering Colombo → Kandy → Ella/Nuwara Eliya → Galle → Colombo. Built for families, couples.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "dubai-skyline-sprint",
    "name": "Dubai Skyline Sprint",
    "type": "international",
    "duration": "3N/4D",
    "price": 28650,
    "priceLabel": "₹28,650–₹2,20,000",
    "totalSeats": 16,
    "bookedSeats": 0,
    "route": "Dubai city → desert → old souks → skyline",
    "category": "International",
    "region": "International",
    "travelType": "International",
    "audience": "Premium short break",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star / similar hotel",
    "itinerarySummary": "D1 Arrival / start at Dubai city | D2 Move to desert / sightseeing | D3 Local excursion / leisure | D4 Departure / return",
    "originalItinerary": "Dubai Short Premium",
    "pageTitle": "Dubai Skyline Sprint | EscapeArc International Tour",
    "metaDescription": "Dubai Skyline Sprint: 3N/4D EscapeArc international experience covering Dubai city → desert → old souks → skyline. Built for premium short break.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  },
  {
    "id": "dubai+abu-dhabi-flash",
    "name": "Dubai+Abu Dhabi Flash",
    "type": "international",
    "duration": "5N/6D",
    "price": 28650,
    "priceLabel": "₹28,650–₹2,20,000",
    "totalSeats": 16,
    "bookedSeats": 0,
    "route": "Dubai → Abu Dhabi → Dubai",
    "category": "International",
    "region": "International",
    "travelType": "International",
    "audience": "Premium UAE holiday",
    "positioning": "SEO-ready travel product",
    "stayType": "3-star / similar hotel",
    "itinerarySummary": "D1 Arrival / check-in | D2 Main sightseeing | D3 Secondary excursion | D4 Leisure / transfer | D5 Local sightseeing / buffer | D6 Departure",
    "originalItinerary": "Dubai+Abu Dhabi Extension",
    "pageTitle": "Dubai+Abu Dhabi Flash | EscapeArc International Tour",
    "metaDescription": "Dubai+Abu Dhabi Flash: 5N/6D EscapeArc international experience covering Dubai → Abu Dhabi → Dubai. Built for premium uae holiday.",
    "provenance": "EscapeArc master database",
    "status": "Current product family"
  }
]
;
